In [16]:
import numpy as np


## LOGIQUE :
Pour resoudre le probleme , on va utiliser l'algebre lineaire pour transformer le probleme en une matrice, et determiner la formule de A^n en fonction de n qui correspond a l'étape n-ieme de la suite.
Pour resoudre ce probleme en utilisera les librairies NUMPY (librairie de calcul) et SYMPY (librairie qui permette utiliser des variables au sens mathematique)

Ceci va nous permettez de reduire la complexité de O(n) (Solution naive, voir naive.cpp) à O(1) (Voir optimise.cpp)



### PARTIE I: DETERMINER LES PROPRIETES DE LA MATRICE A L'AIDE DE LA LIBRAIRIE NUMPY

On transfome la suite de l'exercice en une matrice A

In [17]:
A = np.matrix([[0, 1, 1], [1, 0, 1], [1, 1, 0]])
A

matrix([[0, 1, 1],
        [1, 0, 1],
        [1, 1, 0]])

On determine les valeurs propres et les vecteurs propres a l aide de la librairie numpy

In [18]:
w, v = np.linalg.eig(A)
print("valeurs propres", w)
print("vecteurs propres", v)


valeurs propres [-1.  2. -1.]
vecteurs propres [[-0.81649658  0.57735027  0.19219669]
 [ 0.40824829  0.57735027 -0.7833358 ]
 [ 0.40824829  0.57735027  0.59113912]]


On deduit l'ecriture de A en fonctions des vecteurs propres et evaleurs propres : A=PDP^(-1)
Si on calcule PDP^(-1), on note qu'on obtient A avec des erreurs de calculs

In [19]:
D = np.diag(w) # on transform le spectre en une matrice diagonal


print(v*D*np.linalg.inv(v))

[[-6.21942332e-16  1.00000000e+00  1.00000000e+00]
 [ 1.00000000e+00 -8.26723370e-17  1.00000000e+00]
 [ 1.00000000e+00  1.00000000e+00 -3.50238549e-16]]



### PARTIE 2 : DETERMINER LA MATRICE A^n A L AIDE DE LA LIBRAIRIE SYMPY


In [20]:
import sympy as sp
n = sp.symbols('n') # on definie la  variable x et y sachant que x=(-1)^n y=2^n

On utilise les varibles qu'on a cree pour trouver A^n

In [21]:
Dn = np.diag([valeur_propre**n for valeur_propre in w])
An = v*Dn*np.linalg.inv(v)
print("A^n = ", An)

A^n =  [[-7.76228006213826e-18*(-1.0)**n + 0.666666666666667*(-1.0)**n + 0.333333333333333*2.0**n
  -0.139832806381565*(-1.0)**n - 0.193500526951768*(-1.0)**n + 0.333333333333333*2.0**n
  0.139832806381565*(-1.0)**n - 0.473166139714899*(-1.0)**n + 0.333333333333333*2.0**n]
 [3.1636715646698e-17*(-1.0)**n - 0.333333333333333*(-1.0)**n + 0.333333333333333*2.0**n
  0.569916403190783*(-1.0)**n + 0.0967502634758841*(-1.0)**n + 0.333333333333333*2.0**n
  -0.569916403190782*(-1.0)**n + 0.236583069857449*(-1.0)**n + 0.333333333333333*2.0**n]
 [-2.38744355845598e-17*(-1.0)**n - 0.333333333333333*(-1.0)**n + 0.333333333333333*2.0**n
  -0.430083596809218*(-1.0)**n + 0.0967502634758841*(-1.0)**n + 0.333333333333333*2.0**n
  0.430083596809217*(-1.0)**n + 0.236583069857449*(-1.0)**n + 0.333333333333333*2.0**n]]


Il suffit de faire le produit de A^n*(a0,b0,c0) et remplacer x avec (-1)^n et y avec 2^n:

On resoud l'example 2 de l'exercice :

In [23]:
a0, b0, c0 = 2,3,7
n_ex=5

etape_n = np.dot(An, np.array([a0,b0,c0]))

Reponse = np.sum(etape_n) # exercice demande la somme des montants

Reponse.evalf(subs={n:n_ex})


383.999999999999